version: '3'
services:
  web:
    image: gql-be
    build: .
    command: node -r esm .
    ports:
      - "4000:4000"
    depends_on:
      - "db"
  db:
    image: mongo
    volumes: 
      - "mongodata:/data/db"
    ports:
      - "27017:27017"
    environment:
      - DB=mongodb://mongo:27017/sap-db
      - NODE_ENV=development
volumes:
  mongodata: